name: 'rabbitmq-cluster'
services:
  rabbitmq-node1:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-node1
    hostname: rabbitmq-node1
    environment:
      RABBITMQ_ERLANG_COOKIE: "my_secret_cookie"
      RABBITMQ_NODENAME: "rabbit@rabbitmq-node1"
    ports:
      - "15672:15672"  # 管理界面
      - "5672:5672"    # AMQP 端口
    volumes:
      - rabbitmq-data-node1:/var/lib/rabbitmq
    networks:
      rabbitmq-net:


  rabbitmq-node2:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-node2
    hostname: rabbitmq-node2
    environment:
      RABBITMQ_ERLANG_COOKIE: "my_secret_cookie"
      RABBITMQ_NODENAME: "rabbit@rabbitmq-node2"
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - rabbitmq-data-node2:/var/lib/rabbitmq
    networks:
      rabbitmq-net:


  rabbitmq-node3:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-node3
    hostname: rabbitmq-node3
    environment:
      RABBITMQ_ERLANG_COOKIE: "my_secret_cookie"
      RABBITMQ_NODENAME: "rabbit@rabbitmq-node3"
    ports:
      - "15674:15672"
      - "5674:5672"
    volumes:
      - rabbitmq-data-node3:/var/lib/rabbitmq
    networks:
      rabbitmq-net:


volumes:
  rabbitmq-data-node1:
  rabbitmq-data-node2:
  rabbitmq-data-node3:


networks:
  rabbitmq-net:
    driver: bridge
